---
title: "Visuals"
output: html_document
date: "2023-07-21"
---

```{r setup, include=FALSE}
library(tidyverse)
library(jsonlite)
library(stringr)
library(ggpubr)
library(tidyboot)
library(readxl)
library(brms)
library(ggthemes)
library(writexl)
library(ggdist)
library(sf)
library(grid)
library(geomtextpath)
library(ggridges)
```

```{r}
data <- read_csv("../data/previc_data.csv")%>%
  mutate(age_group = factor(substr(age, 1,1)))
```
## Figure Rasch

```{r}
icc <- readRDS("../saves/icc1_final.rds")%>%
  filter(item == "Kunde")

p_rasch <- icc %>% 
  left_join(data%>%distinct(word, word_type)%>%rename(item = word))%>%
  ggplot(aes(x = theta, y = p,group = item)) +
  geom_hline(yintercept = 0.5, lty = 3, alpha = 0.5)+
  geom_line() +
  scale_y_continuous(breaks = c(0,0.5, 1))+
  labs(x = "Latent ability (expressive language)",
       y = "Probability to answer 'yes'") +
  theme_few()+
  theme(legend.position = c(0.85, 0.2), legend.direction = "vertical", legend.title.align = 0.5, legend.background = element_blank())
```
```{r}
ggsave("../graphs/figr.png", width = 4, height = 3, scale = 1, bg = "white")
```

## Figure 2

```{r}
wtd <- data%>%
  distinct(word, word_type, aoa_rating_german)%>%
  ggplot(aes(x = aoa_rating_german, y = word_type, fill = word_type))+
  geom_density_ridges(alpha = .5, col = "white",jittered_points = TRUE,
    position = position_points_jitter(width = 0.05, height = 0),
    point_shape = '|', point_size = 3, point_alpha = 1, alpha = 0.7, point_color = "black"
)+
  labs(x = "Rated age of acquisition", y = "Word type")+
  scale_fill_colorblind(guide = "none")+
  scale_x_continuous(limits = c(min(data$aoa_rating_german),10))+
  theme_few()
```

```{r}
wac <- data%>%
  group_by(subjID)%>%
  mutate(n = n())%>%
  filter(n == 379)%>%
  select(-n)%>%
  group_by(word, aoa_rating_german, word_type)%>%
  summarise(mean = mean(score))%>%
  ggplot(aes(x = aoa_rating_german, y = mean, col = word_type, fill = word_type))+
  geom_smooth(method = "loess", alpha = .2)+
  #geom_smooth( method = "lm", alpha = .2)+
  ylim(0,1)+
  labs(x = "Rated age of acquisition", y = "Proportion response yes")+
  geom_point(pch = 1, alpha = 0.5)+
  #stat_cor(label.y.npc = "bottom", show.legend = FALSE, aes(label = paste(..r.label..)), cor.coef.name = "r")+
  scale_color_colorblind(name = "Word type", guide = "none")+
  scale_fill_colorblind(name = "Word type", guide = "none")+
  #facet_grid(~word_type)+
  theme_few()
```

```{r}
pac<- data%>%
  group_by(subjID)%>%
  mutate(n = n())%>%
  filter(n == 379)%>%
  select(-n)%>%
  group_by(subjID, age, word_type)%>%
  #group_by(subjID, age)%>%
  summarise(mean = mean(score))%>%
  ggplot(aes(x = age, y = mean, col = word_type))+
  labs(x = "Child age", y = "Proportion response yes")+
  geom_point(pch = 1, alpha = 0.5)+
  geom_smooth(method = "loess", alpha = .2)+
  #stat_cor(label.y.npc = "bottom",label.x.npc = 0.8, show.legend = FALSE, aes(label = paste(..r.label..)), cor.coef.name = "r")+
  scale_color_colorblind(name = "Word type", guide = guide_legend(reverse = TRUE))+
  scale_fill_colorblind(name = "Word type", guide = guide_legend(reverse = TRUE))+
  #facet_grid(~word_type)+
  theme_bw()
```
```{r}
ggarrange(wtd, wac,pac, nrow = 1, labels = c("A","B", "C"), widths = c(0.7,1,1.2))
```
```{r}
ggsave("../graphs/fig2.png", width = 12, height = 3, scale = 1.25, bg = "white")
```

# Figure 3

```{r}
rasch_fit_mode <- readRDS("../saves/rasch_fit_mode.rds")

p_fsi <- rasch_fit_mode%>%
  pivot_wider(names_from = fit_index, values_from = c(mode,uci,lci))%>%
  left_join(data%>%distinct(word, word_type))%>%
  mutate(select = ifelse(word %in% readRDS( "../saves/fit_selected_items.rds"), "include", "exclude"))%>%
  ggplot(., aes(y = mode_infit, x = mode_outfit, pch = select, col = word_type))+
  geom_point(alpha = 0.75)+
  annotate("rect", xmin = 0, xmax = 0.7, ymin = 0, ymax = Inf,
           alpha = .5,fill = "grey")+
  annotate("rect", xmin = 1.3, xmax = Inf, ymin = 0, ymax = Inf,
           alpha = .5,fill = "grey")+
  annotate("rect", ymin = 0, ymax = 0.7, xmin = 0.7, xmax = 1.3,
           alpha = .5,fill = "grey")+
  annotate("rect", ymin = 1.3, ymax = Inf, xmin =0.7, xmax = 1.3,
           alpha = .5,fill = "grey")+
  scale_shape_manual(values = c(4,1))+
  geom_vline(xintercept = c(0.7, 1.3), lty = 3)+
  geom_hline(yintercept = c(0.7, 1.3), lty = 3)+
  labs(x = "Mode Outfit per item", y = "Mode Infit per item")+
  scale_color_colorblind(name = "Word type")+
  theme_few()+
  theme(legend.position = c(0.7, 0.2), legend.title = element_blank(), legend.direction = "vertical", legend.box = "horizontal", legend.background = element_blank())
```

```{r}
p_mc <- readRDS("../saves/model_comparison_size.rds")%>%
  mutate(ratio = abs(elpd_diff) / (2*se_diff))%>%
  mutate(ratio = ifelse( elpd_diff == 0,0,ratio))%>%
  filter(ratio != 0)%>%
  mutate(ratio = ifelse(model == "m2PL", ratio*-1, ratio))%>%
  arrange(iter, size)%>%
  #pivot_longer(cols = c(ratio, correlation), names_to = "type",values_to = "value")%>%
  ggplot(aes(y = factor(size), x = ratio, group = factor(iter)))+
  geom_vline(xintercept = c(-1,1), alpha = 1, lty = 3)+
  geom_vline(xintercept = 0, col = "black", lty = 1, size = 1)+
  geom_point(alpha = .5, size = 3)+
  #geom_line(aes(group = size), alpha = .25)+
  #geom_path(aes(group = iter), alpha = .25)+
  scale_y_discrete(breaks = c(70,75,80,85,90,95,100,125,175))+
  scale_x_continuous( limits = c(-5.5,5.5), breaks = c(-5,-2, -1, 0, 1, 2, 5), labels = c("5.00","2.00","1.00","0.00", "1.00","2.00", "5.00"))+
  scale_color_ptol(guide = "none")+
  #geom_line()+
  #facet_grid(type~. , scales = "free_y")+
  theme_few()+
  theme(panel.grid.minor = element_blank())+
  labs(y = "No. of items in subset", x = expression(paste("Model comparison: ", frac(Delta ~ elpd, "2 *"~SE(Delta ~ elpd)))))+
  annotation_custom(textGrob("1PL wins", 
                             gp=gpar(fontsize=13,
                                     col = "black", 
                                     fontface="bold")),
                    xmin=-3, xmax=-3, ymin="90", ymax="90") +
  annotation_custom(textGrob("2PL wins",
                             gp=gpar(fontsize=13,
                                     col = "black",
                                     fontface="bold")),
                    xmin=3, xmax=3, ymin="90", ymax="90")+
  theme(
        panel.grid.major.y = element_line(size = 0.1))

```

```{r}
final_90_dif_sex <- readRDS("../saves/model_params_irt1_final_90_dif_sex.rds")

pdif <- final_90_dif_sex%>%
  mutate(select = ifelse(item %in% readRDS("../saves/final_items.rds"), "include", "exclude"))%>%
  pivot_wider(names_from = sex, values_from = c(mode,uci,lci))%>%
  ggplot(., aes(x = mode_f, y = mode_m, pch = select, col = select))+
  geom_abline(intercept = 0, slope = 1, lty = 3, alpha = .75)+
  geom_point(size = 2, stroke  = 1, alpha = .75)+
  geom_linerange(aes(ymin = lci_m, ymax = uci_m),  alpha = .25, lty = 1)+
  geom_linerange(aes(xmin = lci_f, xmax = uci_f),  alpha = .25, lty = 1)+
  #geom_text(aes(label = item, x = uci_f +0.2))+
  labs(x = "Group: female", y = "Group: male")+
  scale_shape_manual(values = c(4,1), name = "")+
  scale_x_continuous( limits = c(-5.2,4.6))+
  scale_y_continuous( limits = c(-5.2,4.6))+
  stat_cor(show.legend = FALSE, aes(x = mode_f, y = mode_m, label = paste(..r.label..)),inherit.aes = F, cor.coef.name = "r")+
  scale_color_manual(values = c("#CC6677", "#4477AA"))+
  guides(col = F)+
  theme_few()+
  theme(legend.position = c(0.8, 0.2))

```

```{r}
plot_grid(p_fsi, p_mc, pdif, labels = c("A", "B", "C"), rel_widths = c(1,1,1), nrow = 1)
```

```{r}
ggsave("../graphs/fig3.png", height = 3.5, width = 12, scale = 1.25, bg = "white")
```

# Figure 4

```{r}
icc1_final <- readRDS("../saves/icc1_final.rds")

p_icc <- icc1_final %>% 
  left_join(data%>%distinct(word, word_type)%>%rename(item = word))%>%
  ggplot(aes(x = theta, y = p,group = item, col = word_type)) +
  geom_line() +
  scale_color_colorblind(name = "Word type") +
  labs(x = expression(theta~('ability on the logit scale')),
       y = expression(italic(p)(y==1))) +
  theme_few()+
  theme(legend.position = c(0.85, 0.2), legend.direction = "vertical", legend.title.align = 0.5, legend.background = element_blank())
```


```{r}
tic1_final <- readRDS("../saves/tic1_final.rds")


p_tic <- ggplot(tic1_final, aes(x = theta, y = i)) +
  geom_line() +
  labs(x = expression(theta~('ability on the logit scale')),
       y = "Test information") +
  theme_few()+
  theme(text = element_text(size=10))
```

```{r}
p_iitic <- ggdraw() +
  draw_plot(p_icc)+
  draw_plot(p_tic + theme(plot.background = element_blank()), x = 0.075, y = .68, width = .25, height = .3)
```

```{r}
orev_data <- read_csv("../data/orev_data.csv")

link_data <- data%>%
  filter(word %in% readRDS("../saves/final_items.rds"))%>%
  group_by(subjID)%>%
  summarise(previc = sum(score))%>%
  left_join(orev_data%>%
              group_by(subjID)%>%
              summarise(orev = sum(correct)))%>%
  filter(!is.na(orev))%>%
   ungroup()%>%
  distinct(subjID, .keep_all = T)
```

```{r}
pcpo <- ggplot(link_data, aes(y = previc, x = orev))+
  geom_jitter(pch = 1,  alpha = .5, size = 1, height = 0, width = 0.1)+
  stat_cor(show.legend = FALSE, aes(y = previc, x = orev, label = paste(..r.label..)),inherit.aes = F, cor.coef.name = "r")+
  geom_smooth(method = "lm", inherit.aes = F, aes(y = previc, x = orev), col = "firebrick")+
  labs(y = "PREVIC score", x = "oREV score")+
  theme_few()
```


```{r}
awstr_data <- read_csv("../data/previc_validation.csv")

pcpa <- ggplot(awstr_data, aes(y = previc, x = awst_r_score))+
  geom_jitter(pch = 1,  alpha = .5, size = 1, height = 0, width = 0.1)+
  stat_cor(show.legend = FALSE, aes(y = previc, x = awst_r_score, label = paste(..r.label..)),inherit.aes = F, cor.coef.name = "r")+
  geom_smooth(method = "lm", inherit.aes = F, aes(y = previc, x = awst_r_score), col = "firebrick")+
  labs(y = "PREVIC score", x = "AWST-R score")+
  theme_few()
```


```{r}
m_prev_orev <- data%>%
  filter(word %in% final_items)%>%
  group_by(subjID)%>%
  group_by(age, subjID)%>%
  summarise(sum  = sum(score),
            n = n())%>%
  left_join(orev_data%>%
              group_by(subjID)%>%
              summarise(orev = sum(correct)))%>%
  filter(!is.na(orev))%>%
  ungroup()%>%
  mutate(age = scale(age),
         orev = scale(orev))
  

m1 <- brm(sum |trials(n) ~ age + orev, family = binomial, data = m_prev_orev, chains = 4, cores = 4)
```

```{r}
pme <- m1 %>%
  gather_draws(b_age, b_orev)%>%
  mutate(Predictor = recode(.variable,
                        b_age = "Age",
                        b_orev = "oREV"),
         Predictor = factor(Predictor, levels = c("Age","oREV")))%>%
  ggplot(aes(y = Predictor, x = .value, fill = stat(x) > 0)) +
  stat_halfeye(alpha = .7, .width = c(.95, .80)) +
    labs(x = "Model Estimate", y ="")+
  guides(fill = F)+
  #ggtitle("DV: Reaction Time (25m)")+
  geom_vline(xintercept = 0, linetype = "dashed") +
  scale_fill_manual(values = c("#85AD00", "grey"))+
  theme_few()
```

```{r}
plot_grid(p_iitic, 
          plot_grid(pcpo,pcpa, align = 'hv', ncol = 1, labels = c("B","C")),
          labels = c("A",""), rel_widths = c(3,1))
```

```{r}
ggsave("../graphs/fig4.png", height = 5, width = 10, scale = 1.25, bg = "white")
```
